/**
 * Auth0 Fine Grained Authorization (FGA)/Auth0 FGA SDK for Go
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Website: https://fga.dev
 * Documentation: https://docs.fga.dev
 * Support: https://discord.gg/8naAwJfWN6
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */

package auth0fga

import (
	"encoding/json"
)

// ReadResponse struct for ReadResponse
type ReadResponse struct {
	Tuples *[]Tuple `json:"tuples,omitempty"`
}

// NewReadResponse instantiates a new ReadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReadResponse() *ReadResponse {
	this := ReadResponse{}
	return &this
}

// NewReadResponseWithDefaults instantiates a new ReadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReadResponseWithDefaults() *ReadResponse {
	this := ReadResponse{}
	return &this
}

// GetTuples returns the Tuples field value if set, zero value otherwise.
func (o *ReadResponse) GetTuples() []Tuple {
	if o == nil || o.Tuples == nil {
		var ret []Tuple
		return ret
	}
	return *o.Tuples
}

// GetTuplesOk returns a tuple with the Tuples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReadResponse) GetTuplesOk() (*[]Tuple, bool) {
	if o == nil || o.Tuples == nil {
		return nil, false
	}
	return o.Tuples, true
}

// HasTuples returns a boolean if a field has been set.
func (o *ReadResponse) HasTuples() bool {
	if o != nil && o.Tuples != nil {
		return true
	}

	return false
}

// SetTuples gets a reference to the given []Tuple and assigns it to the Tuples field.
func (o *ReadResponse) SetTuples(v []Tuple) {
	o.Tuples = &v
}

func (o ReadResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tuples != nil {
		toSerialize["tuples"] = o.Tuples
	}
	return json.Marshal(toSerialize)
}

type NullableReadResponse struct {
	value *ReadResponse
	isSet bool
}

func (v NullableReadResponse) Get() *ReadResponse {
	return v.value
}

func (v *NullableReadResponse) Set(val *ReadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReadResponse(val *ReadResponse) *NullableReadResponse {
	return &NullableReadResponse{value: val, isSet: true}
}

func (v NullableReadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
