/**
 * Go SDK for Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Website: https://fga.dev
 * Documentation: https://docs.fga.dev
 * Support: https://discord.gg/8naAwJfWN6
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */

package auth0fga

import (
	"encoding/json"
)

// WriteSettingsRequestParams struct for WriteSettingsRequestParams
type WriteSettingsRequestParams struct {
	Environment *Environment `json:"environment,omitempty"`
}

// NewWriteSettingsRequestParams instantiates a new WriteSettingsRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWriteSettingsRequestParams() *WriteSettingsRequestParams {
	this := WriteSettingsRequestParams{}
	var environment Environment = ENVIRONMENT_UNSPECIFIED
	this.Environment = &environment
	return &this
}

// NewWriteSettingsRequestParamsWithDefaults instantiates a new WriteSettingsRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWriteSettingsRequestParamsWithDefaults() *WriteSettingsRequestParams {
	this := WriteSettingsRequestParams{}
	var environment Environment = ENVIRONMENT_UNSPECIFIED
	this.Environment = &environment
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *WriteSettingsRequestParams) GetEnvironment() Environment {
	if o == nil || o.Environment == nil {
		var ret Environment
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WriteSettingsRequestParams) GetEnvironmentOk() (*Environment, bool) {
	if o == nil || o.Environment == nil {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *WriteSettingsRequestParams) HasEnvironment() bool {
	if o != nil && o.Environment != nil {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given Environment and assigns it to the Environment field.
func (o *WriteSettingsRequestParams) SetEnvironment(v Environment) {
	o.Environment = &v
}

func (o WriteSettingsRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Environment != nil {
		toSerialize["environment"] = o.Environment
	}
	return json.Marshal(toSerialize)
}

type NullableWriteSettingsRequestParams struct {
	value *WriteSettingsRequestParams
	isSet bool
}

func (v NullableWriteSettingsRequestParams) Get() *WriteSettingsRequestParams {
	return v.value
}

func (v *NullableWriteSettingsRequestParams) Set(val *WriteSettingsRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableWriteSettingsRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableWriteSettingsRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWriteSettingsRequestParams(val *WriteSettingsRequestParams) *NullableWriteSettingsRequestParams {
	return &NullableWriteSettingsRequestParams{value: val, isSet: true}
}

func (v NullableWriteSettingsRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWriteSettingsRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
