/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// Auth0FgaCheckRequestParams struct for Auth0FgaCheckRequestParams
type Auth0FgaCheckRequestParams struct {
	TupleKey             *Auth0FgaTupleKey `json:"tuple_key,omitempty"`
	AuthorizationModelId *string           `json:"authorization_model_id,omitempty"`
	// defaults to false. making it true has performance implications. only use for debugging purposes, etc.
	Trace *bool `json:"trace,omitempty"`
}

// NewAuth0FgaCheckRequestParams instantiates a new Auth0FgaCheckRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuth0FgaCheckRequestParams() *Auth0FgaCheckRequestParams {
	this := Auth0FgaCheckRequestParams{}
	return &this
}

// NewAuth0FgaCheckRequestParamsWithDefaults instantiates a new Auth0FgaCheckRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth0FgaCheckRequestParamsWithDefaults() *Auth0FgaCheckRequestParams {
	this := Auth0FgaCheckRequestParams{}
	return &this
}

// GetTupleKey returns the TupleKey field value if set, zero value otherwise.
func (o *Auth0FgaCheckRequestParams) GetTupleKey() Auth0FgaTupleKey {
	if o == nil || o.TupleKey == nil {
		var ret Auth0FgaTupleKey
		return ret
	}
	return *o.TupleKey
}

// GetTupleKeyOk returns a tuple with the TupleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaCheckRequestParams) GetTupleKeyOk() (*Auth0FgaTupleKey, bool) {
	if o == nil || o.TupleKey == nil {
		return nil, false
	}
	return o.TupleKey, true
}

// HasTupleKey returns a boolean if a field has been set.
func (o *Auth0FgaCheckRequestParams) HasTupleKey() bool {
	if o != nil && o.TupleKey != nil {
		return true
	}

	return false
}

// SetTupleKey gets a reference to the given Auth0FgaTupleKey and assigns it to the TupleKey field.
func (o *Auth0FgaCheckRequestParams) SetTupleKey(v Auth0FgaTupleKey) {
	o.TupleKey = &v
}

// GetAuthorizationModelId returns the AuthorizationModelId field value if set, zero value otherwise.
func (o *Auth0FgaCheckRequestParams) GetAuthorizationModelId() string {
	if o == nil || o.AuthorizationModelId == nil {
		var ret string
		return ret
	}
	return *o.AuthorizationModelId
}

// GetAuthorizationModelIdOk returns a tuple with the AuthorizationModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaCheckRequestParams) GetAuthorizationModelIdOk() (*string, bool) {
	if o == nil || o.AuthorizationModelId == nil {
		return nil, false
	}
	return o.AuthorizationModelId, true
}

// HasAuthorizationModelId returns a boolean if a field has been set.
func (o *Auth0FgaCheckRequestParams) HasAuthorizationModelId() bool {
	if o != nil && o.AuthorizationModelId != nil {
		return true
	}

	return false
}

// SetAuthorizationModelId gets a reference to the given string and assigns it to the AuthorizationModelId field.
func (o *Auth0FgaCheckRequestParams) SetAuthorizationModelId(v string) {
	o.AuthorizationModelId = &v
}

// GetTrace returns the Trace field value if set, zero value otherwise.
func (o *Auth0FgaCheckRequestParams) GetTrace() bool {
	if o == nil || o.Trace == nil {
		var ret bool
		return ret
	}
	return *o.Trace
}

// GetTraceOk returns a tuple with the Trace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaCheckRequestParams) GetTraceOk() (*bool, bool) {
	if o == nil || o.Trace == nil {
		return nil, false
	}
	return o.Trace, true
}

// HasTrace returns a boolean if a field has been set.
func (o *Auth0FgaCheckRequestParams) HasTrace() bool {
	if o != nil && o.Trace != nil {
		return true
	}

	return false
}

// SetTrace gets a reference to the given bool and assigns it to the Trace field.
func (o *Auth0FgaCheckRequestParams) SetTrace(v bool) {
	o.Trace = &v
}

func (o Auth0FgaCheckRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TupleKey != nil {
		toSerialize["tuple_key"] = o.TupleKey
	}
	if o.AuthorizationModelId != nil {
		toSerialize["authorization_model_id"] = o.AuthorizationModelId
	}
	if o.Trace != nil {
		toSerialize["trace"] = o.Trace
	}
	return json.Marshal(toSerialize)
}

type NullableAuth0FgaCheckRequestParams struct {
	value *Auth0FgaCheckRequestParams
	isSet bool
}

func (v NullableAuth0FgaCheckRequestParams) Get() *Auth0FgaCheckRequestParams {
	return v.value
}

func (v *NullableAuth0FgaCheckRequestParams) Set(val *Auth0FgaCheckRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableAuth0FgaCheckRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth0FgaCheckRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth0FgaCheckRequestParams(val *Auth0FgaCheckRequestParams) *NullableAuth0FgaCheckRequestParams {
	return &NullableAuth0FgaCheckRequestParams{value: val, isSet: true}
}

func (v NullableAuth0FgaCheckRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth0FgaCheckRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
