/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// Settings struct for Settings
type Settings struct {
	Environment  *Environment   `json:"environment,omitempty"`
	TokenIssuers *[]TokenIssuer `json:"token_issuers,omitempty"`
}

// NewSettings instantiates a new Settings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettings() *Settings {
	this := Settings{}
	var environment Environment = ENVIRONMENT_UNSPECIFIED
	this.Environment = &environment
	return &this
}

// NewSettingsWithDefaults instantiates a new Settings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsWithDefaults() *Settings {
	this := Settings{}
	var environment Environment = ENVIRONMENT_UNSPECIFIED
	this.Environment = &environment
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *Settings) GetEnvironment() Environment {
	if o == nil || o.Environment == nil {
		var ret Environment
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetEnvironmentOk() (*Environment, bool) {
	if o == nil || o.Environment == nil {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *Settings) HasEnvironment() bool {
	if o != nil && o.Environment != nil {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given Environment and assigns it to the Environment field.
func (o *Settings) SetEnvironment(v Environment) {
	o.Environment = &v
}

// GetTokenIssuers returns the TokenIssuers field value if set, zero value otherwise.
func (o *Settings) GetTokenIssuers() []TokenIssuer {
	if o == nil || o.TokenIssuers == nil {
		var ret []TokenIssuer
		return ret
	}
	return *o.TokenIssuers
}

// GetTokenIssuersOk returns a tuple with the TokenIssuers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetTokenIssuersOk() (*[]TokenIssuer, bool) {
	if o == nil || o.TokenIssuers == nil {
		return nil, false
	}
	return o.TokenIssuers, true
}

// HasTokenIssuers returns a boolean if a field has been set.
func (o *Settings) HasTokenIssuers() bool {
	if o != nil && o.TokenIssuers != nil {
		return true
	}

	return false
}

// SetTokenIssuers gets a reference to the given []TokenIssuer and assigns it to the TokenIssuers field.
func (o *Settings) SetTokenIssuers(v []TokenIssuer) {
	o.TokenIssuers = &v
}

func (o Settings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Environment != nil {
		toSerialize["environment"] = o.Environment
	}
	if o.TokenIssuers != nil {
		toSerialize["token_issuers"] = o.TokenIssuers
	}
	return json.Marshal(toSerialize)
}

type NullableSettings struct {
	value *Settings
	isSet bool
}

func (v NullableSettings) Get() *Settings {
	return v.value
}

func (v *NullableSettings) Set(val *Settings) {
	v.value = val
	v.isSet = true
}

func (v NullableSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettings(val *Settings) *NullableSettings {
	return &NullableSettings{value: val, isSet: true}
}

func (v NullableSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
