/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// SettingsSettings struct for SettingsSettings
type SettingsSettings struct {
	Environment  *SettingsEnvironment   `json:"environment,omitempty"`
	TokenIssuers *[]SettingsTokenIssuer `json:"token_issuers,omitempty"`
}

// NewSettingsSettings instantiates a new SettingsSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsSettings() *SettingsSettings {
	this := SettingsSettings{}
	var environment SettingsEnvironment = ENVIRONMENT_UNSPECIFIED
	this.Environment = &environment
	return &this
}

// NewSettingsSettingsWithDefaults instantiates a new SettingsSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsSettingsWithDefaults() *SettingsSettings {
	this := SettingsSettings{}
	var environment SettingsEnvironment = ENVIRONMENT_UNSPECIFIED
	this.Environment = &environment
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *SettingsSettings) GetEnvironment() SettingsEnvironment {
	if o == nil || o.Environment == nil {
		var ret SettingsEnvironment
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsSettings) GetEnvironmentOk() (*SettingsEnvironment, bool) {
	if o == nil || o.Environment == nil {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *SettingsSettings) HasEnvironment() bool {
	if o != nil && o.Environment != nil {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given SettingsEnvironment and assigns it to the Environment field.
func (o *SettingsSettings) SetEnvironment(v SettingsEnvironment) {
	o.Environment = &v
}

// GetTokenIssuers returns the TokenIssuers field value if set, zero value otherwise.
func (o *SettingsSettings) GetTokenIssuers() []SettingsTokenIssuer {
	if o == nil || o.TokenIssuers == nil {
		var ret []SettingsTokenIssuer
		return ret
	}
	return *o.TokenIssuers
}

// GetTokenIssuersOk returns a tuple with the TokenIssuers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsSettings) GetTokenIssuersOk() (*[]SettingsTokenIssuer, bool) {
	if o == nil || o.TokenIssuers == nil {
		return nil, false
	}
	return o.TokenIssuers, true
}

// HasTokenIssuers returns a boolean if a field has been set.
func (o *SettingsSettings) HasTokenIssuers() bool {
	if o != nil && o.TokenIssuers != nil {
		return true
	}

	return false
}

// SetTokenIssuers gets a reference to the given []SettingsTokenIssuer and assigns it to the TokenIssuers field.
func (o *SettingsSettings) SetTokenIssuers(v []SettingsTokenIssuer) {
	o.TokenIssuers = &v
}

func (o SettingsSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Environment != nil {
		toSerialize["environment"] = o.Environment
	}
	if o.TokenIssuers != nil {
		toSerialize["token_issuers"] = o.TokenIssuers
	}
	return json.Marshal(toSerialize)
}

type NullableSettingsSettings struct {
	value *SettingsSettings
	isSet bool
}

func (v NullableSettingsSettings) Get() *SettingsSettings {
	return v.value
}

func (v *NullableSettingsSettings) Set(val *SettingsSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsSettings(val *SettingsSettings) *NullableSettingsSettings {
	return &NullableSettingsSettings{value: val, isSet: true}
}

func (v NullableSettingsSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
