/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// Auth0FgaReadAuthorizationModelResponse struct for Auth0FgaReadAuthorizationModelResponse
type Auth0FgaReadAuthorizationModelResponse struct {
	AuthorizationModel *AuthorizationmodelAuthorizationModel `json:"authorization_model,omitempty"`
}

// NewAuth0FgaReadAuthorizationModelResponse instantiates a new Auth0FgaReadAuthorizationModelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuth0FgaReadAuthorizationModelResponse() *Auth0FgaReadAuthorizationModelResponse {
	this := Auth0FgaReadAuthorizationModelResponse{}
	return &this
}

// NewAuth0FgaReadAuthorizationModelResponseWithDefaults instantiates a new Auth0FgaReadAuthorizationModelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth0FgaReadAuthorizationModelResponseWithDefaults() *Auth0FgaReadAuthorizationModelResponse {
	this := Auth0FgaReadAuthorizationModelResponse{}
	return &this
}

// GetAuthorizationModel returns the AuthorizationModel field value if set, zero value otherwise.
func (o *Auth0FgaReadAuthorizationModelResponse) GetAuthorizationModel() AuthorizationmodelAuthorizationModel {
	if o == nil || o.AuthorizationModel == nil {
		var ret AuthorizationmodelAuthorizationModel
		return ret
	}
	return *o.AuthorizationModel
}

// GetAuthorizationModelOk returns a tuple with the AuthorizationModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaReadAuthorizationModelResponse) GetAuthorizationModelOk() (*AuthorizationmodelAuthorizationModel, bool) {
	if o == nil || o.AuthorizationModel == nil {
		return nil, false
	}
	return o.AuthorizationModel, true
}

// HasAuthorizationModel returns a boolean if a field has been set.
func (o *Auth0FgaReadAuthorizationModelResponse) HasAuthorizationModel() bool {
	if o != nil && o.AuthorizationModel != nil {
		return true
	}

	return false
}

// SetAuthorizationModel gets a reference to the given AuthorizationmodelAuthorizationModel and assigns it to the AuthorizationModel field.
func (o *Auth0FgaReadAuthorizationModelResponse) SetAuthorizationModel(v AuthorizationmodelAuthorizationModel) {
	o.AuthorizationModel = &v
}

func (o Auth0FgaReadAuthorizationModelResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AuthorizationModel != nil {
		toSerialize["authorization_model"] = o.AuthorizationModel
	}
	return json.Marshal(toSerialize)
}

type NullableAuth0FgaReadAuthorizationModelResponse struct {
	value *Auth0FgaReadAuthorizationModelResponse
	isSet bool
}

func (v NullableAuth0FgaReadAuthorizationModelResponse) Get() *Auth0FgaReadAuthorizationModelResponse {
	return v.value
}

func (v *NullableAuth0FgaReadAuthorizationModelResponse) Set(val *Auth0FgaReadAuthorizationModelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuth0FgaReadAuthorizationModelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth0FgaReadAuthorizationModelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth0FgaReadAuthorizationModelResponse(val *Auth0FgaReadAuthorizationModelResponse) *NullableAuth0FgaReadAuthorizationModelResponse {
	return &NullableAuth0FgaReadAuthorizationModelResponse{value: val, isSet: true}
}

func (v NullableAuth0FgaReadAuthorizationModelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth0FgaReadAuthorizationModelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
