/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// Auth0FgaExpandRequestParams struct for Auth0FgaExpandRequestParams
type Auth0FgaExpandRequestParams struct {
	TupleKey             *Auth0FgaTupleKey `json:"tuple_key,omitempty"`
	AuthorizationModelId *string           `json:"authorization_model_id,omitempty"`
}

// NewAuth0FgaExpandRequestParams instantiates a new Auth0FgaExpandRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuth0FgaExpandRequestParams() *Auth0FgaExpandRequestParams {
	this := Auth0FgaExpandRequestParams{}
	return &this
}

// NewAuth0FgaExpandRequestParamsWithDefaults instantiates a new Auth0FgaExpandRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth0FgaExpandRequestParamsWithDefaults() *Auth0FgaExpandRequestParams {
	this := Auth0FgaExpandRequestParams{}
	return &this
}

// GetTupleKey returns the TupleKey field value if set, zero value otherwise.
func (o *Auth0FgaExpandRequestParams) GetTupleKey() Auth0FgaTupleKey {
	if o == nil || o.TupleKey == nil {
		var ret Auth0FgaTupleKey
		return ret
	}
	return *o.TupleKey
}

// GetTupleKeyOk returns a tuple with the TupleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaExpandRequestParams) GetTupleKeyOk() (*Auth0FgaTupleKey, bool) {
	if o == nil || o.TupleKey == nil {
		return nil, false
	}
	return o.TupleKey, true
}

// HasTupleKey returns a boolean if a field has been set.
func (o *Auth0FgaExpandRequestParams) HasTupleKey() bool {
	if o != nil && o.TupleKey != nil {
		return true
	}

	return false
}

// SetTupleKey gets a reference to the given Auth0FgaTupleKey and assigns it to the TupleKey field.
func (o *Auth0FgaExpandRequestParams) SetTupleKey(v Auth0FgaTupleKey) {
	o.TupleKey = &v
}

// GetAuthorizationModelId returns the AuthorizationModelId field value if set, zero value otherwise.
func (o *Auth0FgaExpandRequestParams) GetAuthorizationModelId() string {
	if o == nil || o.AuthorizationModelId == nil {
		var ret string
		return ret
	}
	return *o.AuthorizationModelId
}

// GetAuthorizationModelIdOk returns a tuple with the AuthorizationModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaExpandRequestParams) GetAuthorizationModelIdOk() (*string, bool) {
	if o == nil || o.AuthorizationModelId == nil {
		return nil, false
	}
	return o.AuthorizationModelId, true
}

// HasAuthorizationModelId returns a boolean if a field has been set.
func (o *Auth0FgaExpandRequestParams) HasAuthorizationModelId() bool {
	if o != nil && o.AuthorizationModelId != nil {
		return true
	}

	return false
}

// SetAuthorizationModelId gets a reference to the given string and assigns it to the AuthorizationModelId field.
func (o *Auth0FgaExpandRequestParams) SetAuthorizationModelId(v string) {
	o.AuthorizationModelId = &v
}

func (o Auth0FgaExpandRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TupleKey != nil {
		toSerialize["tuple_key"] = o.TupleKey
	}
	if o.AuthorizationModelId != nil {
		toSerialize["authorization_model_id"] = o.AuthorizationModelId
	}
	return json.Marshal(toSerialize)
}

type NullableAuth0FgaExpandRequestParams struct {
	value *Auth0FgaExpandRequestParams
	isSet bool
}

func (v NullableAuth0FgaExpandRequestParams) Get() *Auth0FgaExpandRequestParams {
	return v.value
}

func (v *NullableAuth0FgaExpandRequestParams) Set(val *Auth0FgaExpandRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableAuth0FgaExpandRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth0FgaExpandRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth0FgaExpandRequestParams(val *Auth0FgaExpandRequestParams) *NullableAuth0FgaExpandRequestParams {
	return &NullableAuth0FgaExpandRequestParams{value: val, isSet: true}
}

func (v NullableAuth0FgaExpandRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth0FgaExpandRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
