/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// UsersetTreeNodes struct for UsersetTreeNodes
type UsersetTreeNodes struct {
	Nodes *[]UsersetTreeNode `json:"nodes,omitempty"`
}

// NewUsersetTreeNodes instantiates a new UsersetTreeNodes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersetTreeNodes() *UsersetTreeNodes {
	this := UsersetTreeNodes{}
	return &this
}

// NewUsersetTreeNodesWithDefaults instantiates a new UsersetTreeNodes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersetTreeNodesWithDefaults() *UsersetTreeNodes {
	this := UsersetTreeNodes{}
	return &this
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *UsersetTreeNodes) GetNodes() []UsersetTreeNode {
	if o == nil || o.Nodes == nil {
		var ret []UsersetTreeNode
		return ret
	}
	return *o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersetTreeNodes) GetNodesOk() (*[]UsersetTreeNode, bool) {
	if o == nil || o.Nodes == nil {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *UsersetTreeNodes) HasNodes() bool {
	if o != nil && o.Nodes != nil {
		return true
	}

	return false
}

// SetNodes gets a reference to the given []UsersetTreeNode and assigns it to the Nodes field.
func (o *UsersetTreeNodes) SetNodes(v []UsersetTreeNode) {
	o.Nodes = &v
}

func (o UsersetTreeNodes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Nodes != nil {
		toSerialize["nodes"] = o.Nodes
	}
	return json.Marshal(toSerialize)
}

type NullableUsersetTreeNodes struct {
	value *UsersetTreeNodes
	isSet bool
}

func (v NullableUsersetTreeNodes) Get() *UsersetTreeNodes {
	return v.value
}

func (v *NullableUsersetTreeNodes) Set(val *UsersetTreeNodes) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersetTreeNodes) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersetTreeNodes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersetTreeNodes(val *UsersetTreeNodes) *NullableUsersetTreeNodes {
	return &NullableUsersetTreeNodes{value: val, isSet: true}
}

func (v NullableUsersetTreeNodes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersetTreeNodes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
