/**
 * Go SDK for Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Website: https://fga.dev
 * Documentation: https://docs.fga.dev
 * Support: https://discord.gg/8naAwJfWN6
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */

package auth0fga

import (
	"encoding/json"
)

// WriteTokenIssuersResponse struct for WriteTokenIssuersResponse
type WriteTokenIssuersResponse struct {
	Id *string `json:"id,omitempty"`
}

// NewWriteTokenIssuersResponse instantiates a new WriteTokenIssuersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWriteTokenIssuersResponse() *WriteTokenIssuersResponse {
	this := WriteTokenIssuersResponse{}
	return &this
}

// NewWriteTokenIssuersResponseWithDefaults instantiates a new WriteTokenIssuersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWriteTokenIssuersResponseWithDefaults() *WriteTokenIssuersResponse {
	this := WriteTokenIssuersResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WriteTokenIssuersResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WriteTokenIssuersResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WriteTokenIssuersResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WriteTokenIssuersResponse) SetId(v string) {
	o.Id = &v
}

func (o WriteTokenIssuersResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableWriteTokenIssuersResponse struct {
	value *WriteTokenIssuersResponse
	isSet bool
}

func (v NullableWriteTokenIssuersResponse) Get() *WriteTokenIssuersResponse {
	return v.value
}

func (v *NullableWriteTokenIssuersResponse) Set(val *WriteTokenIssuersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWriteTokenIssuersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWriteTokenIssuersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWriteTokenIssuersResponse(val *WriteTokenIssuersResponse) *NullableWriteTokenIssuersResponse {
	return &NullableWriteTokenIssuersResponse{value: val, isSet: true}
}

func (v NullableWriteTokenIssuersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWriteTokenIssuersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
