/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// Auth0FgaWriteRequestParams struct for Auth0FgaWriteRequestParams
type Auth0FgaWriteRequestParams struct {
	Writes               *Auth0FgaTupleKeys `json:"writes,omitempty"`
	Deletes              *Auth0FgaTupleKeys `json:"deletes,omitempty"`
	AuthorizationModelId *string            `json:"authorization_model_id,omitempty"`
	LockTuple            *Auth0FgaTuple     `json:"lock_tuple,omitempty"`
}

// NewAuth0FgaWriteRequestParams instantiates a new Auth0FgaWriteRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuth0FgaWriteRequestParams() *Auth0FgaWriteRequestParams {
	this := Auth0FgaWriteRequestParams{}
	return &this
}

// NewAuth0FgaWriteRequestParamsWithDefaults instantiates a new Auth0FgaWriteRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth0FgaWriteRequestParamsWithDefaults() *Auth0FgaWriteRequestParams {
	this := Auth0FgaWriteRequestParams{}
	return &this
}

// GetWrites returns the Writes field value if set, zero value otherwise.
func (o *Auth0FgaWriteRequestParams) GetWrites() Auth0FgaTupleKeys {
	if o == nil || o.Writes == nil {
		var ret Auth0FgaTupleKeys
		return ret
	}
	return *o.Writes
}

// GetWritesOk returns a tuple with the Writes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaWriteRequestParams) GetWritesOk() (*Auth0FgaTupleKeys, bool) {
	if o == nil || o.Writes == nil {
		return nil, false
	}
	return o.Writes, true
}

// HasWrites returns a boolean if a field has been set.
func (o *Auth0FgaWriteRequestParams) HasWrites() bool {
	if o != nil && o.Writes != nil {
		return true
	}

	return false
}

// SetWrites gets a reference to the given Auth0FgaTupleKeys and assigns it to the Writes field.
func (o *Auth0FgaWriteRequestParams) SetWrites(v Auth0FgaTupleKeys) {
	o.Writes = &v
}

// GetDeletes returns the Deletes field value if set, zero value otherwise.
func (o *Auth0FgaWriteRequestParams) GetDeletes() Auth0FgaTupleKeys {
	if o == nil || o.Deletes == nil {
		var ret Auth0FgaTupleKeys
		return ret
	}
	return *o.Deletes
}

// GetDeletesOk returns a tuple with the Deletes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaWriteRequestParams) GetDeletesOk() (*Auth0FgaTupleKeys, bool) {
	if o == nil || o.Deletes == nil {
		return nil, false
	}
	return o.Deletes, true
}

// HasDeletes returns a boolean if a field has been set.
func (o *Auth0FgaWriteRequestParams) HasDeletes() bool {
	if o != nil && o.Deletes != nil {
		return true
	}

	return false
}

// SetDeletes gets a reference to the given Auth0FgaTupleKeys and assigns it to the Deletes field.
func (o *Auth0FgaWriteRequestParams) SetDeletes(v Auth0FgaTupleKeys) {
	o.Deletes = &v
}

// GetAuthorizationModelId returns the AuthorizationModelId field value if set, zero value otherwise.
func (o *Auth0FgaWriteRequestParams) GetAuthorizationModelId() string {
	if o == nil || o.AuthorizationModelId == nil {
		var ret string
		return ret
	}
	return *o.AuthorizationModelId
}

// GetAuthorizationModelIdOk returns a tuple with the AuthorizationModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaWriteRequestParams) GetAuthorizationModelIdOk() (*string, bool) {
	if o == nil || o.AuthorizationModelId == nil {
		return nil, false
	}
	return o.AuthorizationModelId, true
}

// HasAuthorizationModelId returns a boolean if a field has been set.
func (o *Auth0FgaWriteRequestParams) HasAuthorizationModelId() bool {
	if o != nil && o.AuthorizationModelId != nil {
		return true
	}

	return false
}

// SetAuthorizationModelId gets a reference to the given string and assigns it to the AuthorizationModelId field.
func (o *Auth0FgaWriteRequestParams) SetAuthorizationModelId(v string) {
	o.AuthorizationModelId = &v
}

// GetLockTuple returns the LockTuple field value if set, zero value otherwise.
func (o *Auth0FgaWriteRequestParams) GetLockTuple() Auth0FgaTuple {
	if o == nil || o.LockTuple == nil {
		var ret Auth0FgaTuple
		return ret
	}
	return *o.LockTuple
}

// GetLockTupleOk returns a tuple with the LockTuple field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaWriteRequestParams) GetLockTupleOk() (*Auth0FgaTuple, bool) {
	if o == nil || o.LockTuple == nil {
		return nil, false
	}
	return o.LockTuple, true
}

// HasLockTuple returns a boolean if a field has been set.
func (o *Auth0FgaWriteRequestParams) HasLockTuple() bool {
	if o != nil && o.LockTuple != nil {
		return true
	}

	return false
}

// SetLockTuple gets a reference to the given Auth0FgaTuple and assigns it to the LockTuple field.
func (o *Auth0FgaWriteRequestParams) SetLockTuple(v Auth0FgaTuple) {
	o.LockTuple = &v
}

func (o Auth0FgaWriteRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Writes != nil {
		toSerialize["writes"] = o.Writes
	}
	if o.Deletes != nil {
		toSerialize["deletes"] = o.Deletes
	}
	if o.AuthorizationModelId != nil {
		toSerialize["authorization_model_id"] = o.AuthorizationModelId
	}
	if o.LockTuple != nil {
		toSerialize["lock_tuple"] = o.LockTuple
	}
	return json.Marshal(toSerialize)
}

type NullableAuth0FgaWriteRequestParams struct {
	value *Auth0FgaWriteRequestParams
	isSet bool
}

func (v NullableAuth0FgaWriteRequestParams) Get() *Auth0FgaWriteRequestParams {
	return v.value
}

func (v *NullableAuth0FgaWriteRequestParams) Set(val *Auth0FgaWriteRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableAuth0FgaWriteRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth0FgaWriteRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth0FgaWriteRequestParams(val *Auth0FgaWriteRequestParams) *NullableAuth0FgaWriteRequestParams {
	return &NullableAuth0FgaWriteRequestParams{value: val, isSet: true}
}

func (v NullableAuth0FgaWriteRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth0FgaWriteRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
