/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// Auth0FgaWriteAuthorizationModelResponse struct for Auth0FgaWriteAuthorizationModelResponse
type Auth0FgaWriteAuthorizationModelResponse struct {
	AuthorizationModelId *string `json:"authorization_model_id,omitempty"`
}

// NewAuth0FgaWriteAuthorizationModelResponse instantiates a new Auth0FgaWriteAuthorizationModelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuth0FgaWriteAuthorizationModelResponse() *Auth0FgaWriteAuthorizationModelResponse {
	this := Auth0FgaWriteAuthorizationModelResponse{}
	return &this
}

// NewAuth0FgaWriteAuthorizationModelResponseWithDefaults instantiates a new Auth0FgaWriteAuthorizationModelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth0FgaWriteAuthorizationModelResponseWithDefaults() *Auth0FgaWriteAuthorizationModelResponse {
	this := Auth0FgaWriteAuthorizationModelResponse{}
	return &this
}

// GetAuthorizationModelId returns the AuthorizationModelId field value if set, zero value otherwise.
func (o *Auth0FgaWriteAuthorizationModelResponse) GetAuthorizationModelId() string {
	if o == nil || o.AuthorizationModelId == nil {
		var ret string
		return ret
	}
	return *o.AuthorizationModelId
}

// GetAuthorizationModelIdOk returns a tuple with the AuthorizationModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaWriteAuthorizationModelResponse) GetAuthorizationModelIdOk() (*string, bool) {
	if o == nil || o.AuthorizationModelId == nil {
		return nil, false
	}
	return o.AuthorizationModelId, true
}

// HasAuthorizationModelId returns a boolean if a field has been set.
func (o *Auth0FgaWriteAuthorizationModelResponse) HasAuthorizationModelId() bool {
	if o != nil && o.AuthorizationModelId != nil {
		return true
	}

	return false
}

// SetAuthorizationModelId gets a reference to the given string and assigns it to the AuthorizationModelId field.
func (o *Auth0FgaWriteAuthorizationModelResponse) SetAuthorizationModelId(v string) {
	o.AuthorizationModelId = &v
}

func (o Auth0FgaWriteAuthorizationModelResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AuthorizationModelId != nil {
		toSerialize["authorization_model_id"] = o.AuthorizationModelId
	}
	return json.Marshal(toSerialize)
}

type NullableAuth0FgaWriteAuthorizationModelResponse struct {
	value *Auth0FgaWriteAuthorizationModelResponse
	isSet bool
}

func (v NullableAuth0FgaWriteAuthorizationModelResponse) Get() *Auth0FgaWriteAuthorizationModelResponse {
	return v.value
}

func (v *NullableAuth0FgaWriteAuthorizationModelResponse) Set(val *Auth0FgaWriteAuthorizationModelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuth0FgaWriteAuthorizationModelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth0FgaWriteAuthorizationModelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth0FgaWriteAuthorizationModelResponse(val *Auth0FgaWriteAuthorizationModelResponse) *NullableAuth0FgaWriteAuthorizationModelResponse {
	return &NullableAuth0FgaWriteAuthorizationModelResponse{value: val, isSet: true}
}

func (v NullableAuth0FgaWriteAuthorizationModelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth0FgaWriteAuthorizationModelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
