/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// Auth0FgaReadAuthorizationModelsResponse struct for Auth0FgaReadAuthorizationModelsResponse
type Auth0FgaReadAuthorizationModelsResponse struct {
	AuthorizationModelIds *[]string `json:"authorization_model_ids,omitempty"`
	ContinuationToken     *string   `json:"continuation_token,omitempty"`
}

// NewAuth0FgaReadAuthorizationModelsResponse instantiates a new Auth0FgaReadAuthorizationModelsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuth0FgaReadAuthorizationModelsResponse() *Auth0FgaReadAuthorizationModelsResponse {
	this := Auth0FgaReadAuthorizationModelsResponse{}
	return &this
}

// NewAuth0FgaReadAuthorizationModelsResponseWithDefaults instantiates a new Auth0FgaReadAuthorizationModelsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth0FgaReadAuthorizationModelsResponseWithDefaults() *Auth0FgaReadAuthorizationModelsResponse {
	this := Auth0FgaReadAuthorizationModelsResponse{}
	return &this
}

// GetAuthorizationModelIds returns the AuthorizationModelIds field value if set, zero value otherwise.
func (o *Auth0FgaReadAuthorizationModelsResponse) GetAuthorizationModelIds() []string {
	if o == nil || o.AuthorizationModelIds == nil {
		var ret []string
		return ret
	}
	return *o.AuthorizationModelIds
}

// GetAuthorizationModelIdsOk returns a tuple with the AuthorizationModelIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaReadAuthorizationModelsResponse) GetAuthorizationModelIdsOk() (*[]string, bool) {
	if o == nil || o.AuthorizationModelIds == nil {
		return nil, false
	}
	return o.AuthorizationModelIds, true
}

// HasAuthorizationModelIds returns a boolean if a field has been set.
func (o *Auth0FgaReadAuthorizationModelsResponse) HasAuthorizationModelIds() bool {
	if o != nil && o.AuthorizationModelIds != nil {
		return true
	}

	return false
}

// SetAuthorizationModelIds gets a reference to the given []string and assigns it to the AuthorizationModelIds field.
func (o *Auth0FgaReadAuthorizationModelsResponse) SetAuthorizationModelIds(v []string) {
	o.AuthorizationModelIds = &v
}

// GetContinuationToken returns the ContinuationToken field value if set, zero value otherwise.
func (o *Auth0FgaReadAuthorizationModelsResponse) GetContinuationToken() string {
	if o == nil || o.ContinuationToken == nil {
		var ret string
		return ret
	}
	return *o.ContinuationToken
}

// GetContinuationTokenOk returns a tuple with the ContinuationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth0FgaReadAuthorizationModelsResponse) GetContinuationTokenOk() (*string, bool) {
	if o == nil || o.ContinuationToken == nil {
		return nil, false
	}
	return o.ContinuationToken, true
}

// HasContinuationToken returns a boolean if a field has been set.
func (o *Auth0FgaReadAuthorizationModelsResponse) HasContinuationToken() bool {
	if o != nil && o.ContinuationToken != nil {
		return true
	}

	return false
}

// SetContinuationToken gets a reference to the given string and assigns it to the ContinuationToken field.
func (o *Auth0FgaReadAuthorizationModelsResponse) SetContinuationToken(v string) {
	o.ContinuationToken = &v
}

func (o Auth0FgaReadAuthorizationModelsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AuthorizationModelIds != nil {
		toSerialize["authorization_model_ids"] = o.AuthorizationModelIds
	}
	if o.ContinuationToken != nil {
		toSerialize["continuation_token"] = o.ContinuationToken
	}
	return json.Marshal(toSerialize)
}

type NullableAuth0FgaReadAuthorizationModelsResponse struct {
	value *Auth0FgaReadAuthorizationModelsResponse
	isSet bool
}

func (v NullableAuth0FgaReadAuthorizationModelsResponse) Get() *Auth0FgaReadAuthorizationModelsResponse {
	return v.value
}

func (v *NullableAuth0FgaReadAuthorizationModelsResponse) Set(val *Auth0FgaReadAuthorizationModelsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuth0FgaReadAuthorizationModelsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth0FgaReadAuthorizationModelsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth0FgaReadAuthorizationModelsResponse(val *Auth0FgaReadAuthorizationModelsResponse) *NullableAuth0FgaReadAuthorizationModelsResponse {
	return &NullableAuth0FgaReadAuthorizationModelsResponse{value: val, isSet: true}
}

func (v NullableAuth0FgaReadAuthorizationModelsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth0FgaReadAuthorizationModelsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
