/*
 * Auth0 Fine Grained Authorization (FGA)
 *
 * Auth0 Fine Grained Authorization (FGA) is an early-stage product we are building at Auth0 as part of Auth0Lab to solve fine-grained authorization at scale. If you are interested in learning more about our plans, please reach out via our Discord chat.  The limits and information described in this document is subject to change.
 *
 * API version: 0.1
 * Contact: https://discord.gg/8naAwJfWN6
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth0fga

import (
	"encoding/json"
)

// AuthorizationmodelTypeDefinitions struct for AuthorizationmodelTypeDefinitions
type AuthorizationmodelTypeDefinitions struct {
	TypeDefinitions *[]AuthorizationmodelTypeDefinition `json:"type_definitions,omitempty"`
}

// NewAuthorizationmodelTypeDefinitions instantiates a new AuthorizationmodelTypeDefinitions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationmodelTypeDefinitions() *AuthorizationmodelTypeDefinitions {
	this := AuthorizationmodelTypeDefinitions{}
	return &this
}

// NewAuthorizationmodelTypeDefinitionsWithDefaults instantiates a new AuthorizationmodelTypeDefinitions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationmodelTypeDefinitionsWithDefaults() *AuthorizationmodelTypeDefinitions {
	this := AuthorizationmodelTypeDefinitions{}
	return &this
}

// GetTypeDefinitions returns the TypeDefinitions field value if set, zero value otherwise.
func (o *AuthorizationmodelTypeDefinitions) GetTypeDefinitions() []AuthorizationmodelTypeDefinition {
	if o == nil || o.TypeDefinitions == nil {
		var ret []AuthorizationmodelTypeDefinition
		return ret
	}
	return *o.TypeDefinitions
}

// GetTypeDefinitionsOk returns a tuple with the TypeDefinitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationmodelTypeDefinitions) GetTypeDefinitionsOk() (*[]AuthorizationmodelTypeDefinition, bool) {
	if o == nil || o.TypeDefinitions == nil {
		return nil, false
	}
	return o.TypeDefinitions, true
}

// HasTypeDefinitions returns a boolean if a field has been set.
func (o *AuthorizationmodelTypeDefinitions) HasTypeDefinitions() bool {
	if o != nil && o.TypeDefinitions != nil {
		return true
	}

	return false
}

// SetTypeDefinitions gets a reference to the given []AuthorizationmodelTypeDefinition and assigns it to the TypeDefinitions field.
func (o *AuthorizationmodelTypeDefinitions) SetTypeDefinitions(v []AuthorizationmodelTypeDefinition) {
	o.TypeDefinitions = &v
}

func (o AuthorizationmodelTypeDefinitions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TypeDefinitions != nil {
		toSerialize["type_definitions"] = o.TypeDefinitions
	}
	return json.Marshal(toSerialize)
}

type NullableAuthorizationmodelTypeDefinitions struct {
	value *AuthorizationmodelTypeDefinitions
	isSet bool
}

func (v NullableAuthorizationmodelTypeDefinitions) Get() *AuthorizationmodelTypeDefinitions {
	return v.value
}

func (v *NullableAuthorizationmodelTypeDefinitions) Set(val *AuthorizationmodelTypeDefinitions) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationmodelTypeDefinitions) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationmodelTypeDefinitions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationmodelTypeDefinitions(val *AuthorizationmodelTypeDefinitions) *NullableAuthorizationmodelTypeDefinitions {
	return &NullableAuthorizationmodelTypeDefinitions{value: val, isSet: true}
}

func (v NullableAuthorizationmodelTypeDefinitions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationmodelTypeDefinitions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
